spring:
  datasource:
    url: jdbc:mysql://localhost:3306/traindb
    username: root
    password: DD53joexcmk
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false

