spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train
    username: user
    password: AstonTrain2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false
  mail:
    host: smtp.mail.ru
    username: 26roma261994@mail.ru
    password: S1yL5HeiFmHdBfGaQ5GH
    port: 465
    protocol: smtps
    debug: true

